### ISSUE TITLE
Upload ipa file, please, to root directory. For jailbreak users

### ISSUE THREAD

**Issue by Yanpas** [m4rr/mauth#1]
Not everyone has OS X to build your app from source. Thanks!
We [downloaders] will provide you feedback :)

**Comment by m4rr** [comment]
What iOS version are you using?

**Comment by Yanpas** [comment]
@m4rr IOS 8.1

**Comment by m4rr** [comment]
@Yanpas try fresh 2.41 build: https://dl.dropboxusercontent.com/u/6342770/mauth.2.41.ipa
